issue_tracker/accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('list/', UserListView.as_view(), name='list'),
    path("<int:pk>/edit/", UserChangeView.as_view(), name="edit_profile"),
    path("<int:pk>/change-password/", ChangePasswordView.as_view(), name="change_password")
]

issue_tracker/issue_tracker/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls)
]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path('accounts/', include('accounts.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/webapp/urls.py
from django.urls import path
from webapp import views as webview
from accounts.views import RemoveFromProjectView, AddToProjectView

app_name = "webapp"

urlpatterns = [
    path('', webview.IndexView.as_view(), name='index'),
    path('issue/<int:issue_pk>/', webview.IssueView.as_view(), name='issue_detail'),
    path('issue/add/', webview.AddIssue.as_view(), name="issue_add"),
    path('issue/edit/<int:pk>/', webview.UpdateIssue.as_view(), name="issue_update"),
    path('issue/delete/<int:pk>', webview.DeleteIssue.as_view(), name="issue_delete"),
    path('projects-list/', webview.ProjectListView.as_view(), name='project_list'),
    path('detailed/<int:pk>', webview.ProjectDetailedView.as_view(), name='project_detail'),
    path('project/add', webview.ProjectCreateView.as_view(), name='project_add'),
    path('project/delete/<int:pk>', webview.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/update/<int:pk>', webview.ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/issue/add', webview.ProjectCreateIssue.as_view(), name='project_add_issue'),
    path('project/<int:project_pk>/account/remove/',
         RemoveFromProjectView.as_view(), name='project_remove_user'),
    path('project/<int:project_pk>/account/add/', AddToProjectView.as_view(), name='project_add_user')
]

issue_tracker/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name="profile",
        on_delete=models.CASCADE,
        verbose_name=_("ProfileUser")
    )
    avatar = models.ImageField(null=True, blank=True,
                               upload_to="avatars", verbose_name=_("ProfileAvatar"))
    github_link = models.URLField(null=True, blank=True,
                                  verbose_name=_("ProfileGithub"))
    about = models.TextField(null=True, blank=True,
                             verbose_name=_("ProfileAbout"))

    class Meta:
        verbose_name = _("ProfileVerboseName")
        verbose_name_plural = _("ProfilePluralName")

issue_tracker/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from accounts.models import Profile


class RegistrationForm(UserCreationForm):
    email = forms.CharField(label=_("RegistrationFormEmail"), required=True)
    username = forms.CharField(label=_("RegistraionFormUsername"), required=True)
    first_name = forms.CharField(label=_("RegistrationFormFirstName"))
    last_name = forms.CharField(label=_("RegistrationFormLastName"))
    password2 = forms.CharField(label=_("RegistrationFormConfirmationPassword"))

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        if first_name == "" and last_name == "":
            raise ValidationError("First name or Last name is required")
        return cleaned_data

    class Meta(UserCreationForm.Meta):
        fields = ["username", "first_name",
                  "last_name", "email", "password1", "password2"]


class UserChangeForm(forms.ModelForm):
    first_name = forms.CharField(label=_("UserChangeFormFirstName"))
    last_name = forms.CharField(label=_("UserChangeFormLastName"))
    email = forms.CharField(label=_("UserChangeFormEmail"), widget=forms.EmailInput)

    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "email"]


class ProfileChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label=_("ProfileAvatar"))
    github_link = forms.URLField(label=_("ProfileGithub"))
    about = forms.CharField(label=_("ProfileAbout"), widget=forms.Textarea)

    class Meta:
        model = Profile
        exclude = ["user"]


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(label=_("PasswordFormOldPass"), strip=False,
                                   widget=forms.PasswordInput)
    password = forms.CharField(label=_("PasswordFormNewPassword"), strip=False,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(label=_("PasswordFormConfirmationPass"), strip=False,
                                       widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data["password"]
        password_confirm = self.cleaned_data["password_confirm"]
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords are not equal")
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Wrong old password")
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()

        return user

    class Meta:
        model = get_user_model()
        fields = ["old_password", "password", "password_confirm"]

issue_tracker/accounts/views.py
from django.contrib.auth import login, authenticate, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, reverse, get_object_or_404
from django.views.generic import View, CreateView, DetailView, ListView, UpdateView
from django.http import HttpResponseRedirect
from accounts.forms import RegistrationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile
from webapp.models import Project
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.list import MultipleObjectMixin


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "registration/login.html")

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        next_path = request.POST.get("next")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if next_path:
                return HttpResponseRedirect(next_path)
            return redirect("webapp:index")
        return render(request, "registration/login.html", {"has_error": True})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("webapp:index")


class RegisterView(CreateView):
    model = User
    template_name = "registration/register.html"
    form_class = RegistrationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class RemoveFromProjectView(UserPassesTestMixin, View):
    template_name = 'remove.html'

    def get_object(self):
        pk = self.kwargs.get("project_pk")
        return Project.objects.get(pk=pk)

    def test_func(self):
        return self.request.user.has_perm('auth.delete_user') and self.request.user in self.get_object().users.all()

    def get(self, request, *args, **kwargs):
        project_id = kwargs.get("project_pk")
        user_id = request.GET.get("user_id")
        project = get_object_or_404(Project, id=project_id)
        user = User.objects.get(id=user_id)
        return render(request, self.template_name, {"user": user, "project": project})

    def post(self, request, *args, **kwargs):
        project_id = kwargs.get("project_pk")
        project = get_object_or_404(Project, id=project_id)
        user_id = request.POST.get("user_id")
        user = get_object_or_404(User, id=user_id)
        choice = request.POST.get("choice")
        if choice == "Yes":
            project.users.remove(user)
        return redirect("webapp:project_detail", pk=project.pk)


class AddToProjectView(UserPassesTestMixin, View):
    template_name = 'add.html'

    def get_object(self):
        pk = self.kwargs.get("project_pk")
        return Project.objects.get(pk=pk)

    def test_func(self):
        return self.request.user in self.get_object().users.all() and self.request.user.has_perm('auth.add_user')

    def get(self, request, *args, **kwargs):
        project_id = kwargs.get("project_pk")
        project = get_object_or_404(Project, id=project_id)
        return render(request, self.template_name, {"project": project})

    def post(self, request, *args, **kwargs):
        project_id = kwargs.get("project_pk")
        project = get_object_or_404(Project, id=project_id)
        user_request = request.POST.get("user_id")
        user = None
        try:
            user = User.objects.get(username=user_request)
            project.users.add(user)
            return redirect("webapp:project_detail", pk=project.pk)
        except User.DoesNotExist as n:
            return render(request, self.template_name, {"project": project, "error": n})


class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = "user_detail.html"
    context_object_name = "user_obj"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        object_list = Project.objects.filter(users__username__icontains=self.object.username)
        context = super(UserDetailView, self).get_context_data(object_list=object_list, **kwargs)
        return context


class UserListView(PermissionRequiredMixin, ListView):
    model = get_user_model()
    template_name = "users_list.html"
    context_object_name = "users_list"
    paginate_by = 10
    permission_required = "accounts.view_profile"


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = "edit_profile.html"
    context_object_name = "user_obj"

    def test_func(self):
        return self.request.user == self.get_object() or \
               self.request.user.is_superuser or self.request.user.groups.filter(name="admins")

    def get_profile_form(self):
        form_kwargs = {"instance": self.object.profile}
        if self.request.method == "POST":
            form_kwargs["data"] = self.request.POST
            form_kwargs["files"] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user_form = self.get_form()
        profile_form = self.get_profile_form()
        if user_form.is_valid() and profile_form.is_valid():
            return self.form_valid(user_form, profile_form)
        else:
            return self.form_invalid(user_form, profile_form)

    def form_valid(self, user_form, profile_form):
        result = super().form_valid(user_form)
        profile_form.save()
        return result

    def form_invalid(self, user_form, profile_form):
        context = self.get_context_data(
            user_form=user_form,
            profile_form=profile_form
        )
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = self.get_profile_form()
            kwargs["user_form"] = self.get_form()
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.object.pk})


class ChangePasswordView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = "change_password.html"
    context_object_name = "user_obj"

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.instance)
        return redirect("accounts:profile", pk=self.get_object().pk)

    def test_func(self):
        return self.request.user == self.get_object() or \
               self.request.user.is_superuser or self.request.user.groups.filter(name="admins")

issue_tracker/accounts/templates/add.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Add user" %}
{% endblock %}

{% block content %}
    <h1>{% trans "Add user to the" %} {{ project }} {% trans "project" %}:</h1>
    <form action="{% url 'webapp:project_add_user' project.pk %}" class="mt-5" method="post">
        {% csrf_token %}
        <label>
            {% trans "Input username:" %}
            <input class="form-control" type="text" name="user_id">
        </label>
        <button class="btn btn-primary">{% trans "Submit" %}</button>
    </form>
    <p class="error_msg">{{ error }}</p>
{% endblock %}

issue_tracker/accounts/templates/change_password.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content %}
    <h1 class="mb-4">{% trans "Change password for" %} {{ user_obj.username }}</h1>
    <form action="{% url "accounts:change_password" user_obj.pk %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">{% trans "Change" %}</button>
    </form>
{% endblock %}

issue_tracker/accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block title %}{% trans "Edit profile" %}{% endblock %}

{% block content %}
    <h1 class="mb-4">{% trans "Edit profile" %}</h1>

    <form action="{% url "accounts:edit_profile" user_obj.pk %}"
          method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        <button class="btn btn-primary">{% trans "Edit" %}</button>
    </form>
{% endblock %}

issue_tracker/accounts/templates/remove.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Remove user" %}
{% endblock %}

{% block content %}
        <div class="container">
            <h1 class="text-center">{% trans "Are you sure want to delete" %} {{ user }} {% trans "from the project" %} "{{ project }}"?</h1>
            <form action="{% url 'webapp:project_remove_user' project.pk %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col text-center">
                        <button class="btn btn-primary btn-block mt-3" name="choice" value="Yes">{% trans "Yes" %}</button>
                        <input type="hidden" name="user_id" value="{{ user.pk }}">
                        <button class="btn btn-secondary btn-block mt-3">{% trans "No" %}</button>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

issue_tracker/accounts/templates/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ user_obj.username }} {% trans "'s profile" %}{% endblock %}
{% block content %}
    <h1>{{ user_obj.username }} {% trans "'s profile" %}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250">
    {% else %}
        <img class="avatar" src="https://pa1.narvii.com/6406/44636fa8fa6911b454828100d653c1e2a428a422_hq.gif" width="250">
    {% endif %}

    <p class="mt-4"><b>{% trans "Username:" %} </b> {{ user_obj.username }}</p>
    {% if user_obj.first_name %}
    <p><b>{% trans "First name:" %} </b> {{ user_obj.first_name }}</p>
    {% endif %}
    {% if user_obj.last_name %}
    <p><b>{% trans "Last name:" %} </b> {{ user_obj.last_name }}</p>
    {% endif %}
    <p><b>{% trans "Email:" %} </b> {{ user_obj.email }}</p>
    {% if user_obj.profile.github_link %}
    <p><b>{% trans "Github page:" %} </b> <a href="{{ user_obj.profile.github_link }}">{{ user_obj.profile.github_link }}</a></p>
    {% endif %}
    {% ifequal user user_obj %}
        <p>
            <a class="btn btn-primary" href="{% url "accounts:edit_profile" user_obj.pk %}">
                {% trans "Edit account" %} <i class="bi bi-pencil-square"></i>
            </a>
            <a class="btn btn-primary" href="{% url "accounts:change_password" user_obj.pk %}">
                {% trans "Change password" %} <i class="bi bi-pencil-square"></i>
            </a>
        </p>
    {% endifequal %}
    {% if user_obj.profile.aboout %}
    <h2>{% trans "About me" %}:</h2>
    <p>{{ user_obj.profile.about }}</p>
    {% endif %}
    <h3 class="text-center m-4">{% trans "My projects" %}: </h3>
    {% include "partial/project_list.html" %}
    {% include "partial/pagination.html" %}
{% endblock %}

issue_tracker/accounts/templates/users_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "UserList" %}{% endblock %}

{% block content %}
    <table class="table">
  <thead class="bg-primary text-white">
    <tr>
      <th scope="col">{% trans "id" %}</th>
      <th scope="col">{% trans "Username" %}</th>
      <th scope="col">{% trans "Email" %}</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users_list %}
    <tr>
      <th scope="row">{{ user.pk }}</th>
      <td><a href="{% url "accounts:profile" user.pk %}">{{ user.username }}</a></td>
      <td>{{ user.email }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% include "partial/pagination.html" %}
{% endblock %}