issue_tracker/accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('list/', UserListView.as_view(), name='list'),
    path("<int:pk>/edit/", UserChangeView.as_view(), name="edit_profile"),
    path("<int:pk>/change-password/", ChangePasswordView.as_view(), name="change_password")
]

issue_tracker/issue_tracker/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls)
]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path('accounts/', include('accounts.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/webapp/urls.py
from django.urls import path
from webapp import views as webview
from accounts.views import RemoveFromProjectView, AddToProjectView

app_name = "webapp"

urlpatterns = [
    path('', webview.IndexView.as_view(), name='index'),
    path('issue/<int:issue_pk>/', webview.IssueView.as_view(), name='issue_detail'),
    path('issue/add/', webview.AddIssue.as_view(), name="issue_add"),
    path('issue/edit/<int:pk>/', webview.UpdateIssue.as_view(), name="issue_update"),
    path('issue/delete/<int:pk>', webview.DeleteIssue.as_view(), name="issue_delete"),
    path('projects-list/', webview.ProjectListView.as_view(), name='project_list'),
    path('detailed/<int:pk>', webview.ProjectDetailedView.as_view(), name='project_detail'),
    path('project/add', webview.ProjectCreateView.as_view(), name='project_add'),
    path('project/delete/<int:pk>', webview.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/update/<int:pk>', webview.ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/issue/add', webview.ProjectCreateIssue.as_view(), name='project_add_issue'),
    path('project/<int:project_pk>/account/remove/',
         RemoveFromProjectView.as_view(), name='project_remove_user'),
    path('project/<int:project_pk>/account/add/', AddToProjectView.as_view(), name='project_add_user')
]

issue_tracker/webapp/models.py
from django.core.validators import BaseValidator
from django.db import models
from django.utils.deconstruct import deconstructible
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

@deconstructible
class MaxValueValidator(BaseValidator):
    message = "Value %(value)s has length %(show_value)d. Length should be less than %(limit_value)d"

    def clean(self, x):
        return len(x)

    def compare(self, a, b):
        return a > b


@deconstructible
class MinValueValidator(BaseValidator):
    message = "Value %(value)s has length %(show_value)d. Min Length should be more than %(limit_value)d"

    def clean(self, x):
        return len(x)

    def compare(self, a, b):
        return a < b


class Type(models.Model):
    title = models.CharField(max_length=20, null=False, blank=False, verbose_name=_('TypeTitle'))

    def __str__(self):
        return f'{self.title}'


class Status(models.Model):
    title = models.CharField(max_length=20, null=False, blank=False, verbose_name=_('StatusTitle'))

    def __str__(self):
        return f'{self.title}'


class Issue(models.Model):
    summary = models.CharField(max_length=30, validators=[MaxValueValidator(30)], null=False, blank=False,
                               verbose_name=_('IssueSummary'))
    description = models.TextField(max_length=2000, validators=[MinValueValidator(100)], blank=True, null=True,
                                   verbose_name=_('IssueDescription'))
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, verbose_name=_('IssueStatus'),
                               related_name='issues')
    type = models.ManyToManyField('webapp.Type', related_name='issues')
    creation_time = models.DateTimeField(auto_now_add=True, verbose_name=_('IssueCreationTime'))
    update_time = models.DateTimeField(auto_now=True, verbose_name=_('IssueUpdateTime'))
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.summary} ({self.status}, {self.type.get()})'


class Project(models.Model):
    start_date = models.DateField(verbose_name=_("ProjectStartDate"))
    finish_date = models.DateField(blank=True, verbose_name=_("ProjectFinishDate"))
    project_name = models.CharField(max_length=30, verbose_name=_("ProjectName"))
    project_summary = models.TextField(verbose_name=_("ProjectSummary"))
    users = models.ManyToManyField(User, verbose_name=_("ProjectUsers"))

    def __str__(self):
        return f'{self.project_name}'

issue_tracker/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import Issue, Status, Type, Project
from django.utils.translation import gettext_lazy as _
from modeltranslation.forms import TranslationModelForm

special_attributes = {"class": "form-control"}


class IssueForm(TranslationModelForm):
    summary = forms.CharField(widget=widgets.TextInput(attrs=special_attributes), label=_("IssueFormSummary"))
    description = forms.CharField(widget=widgets.Textarea(attrs=special_attributes), label=_("IssueFormDescription"))
    status = forms.ModelChoiceField(queryset=Status.objects.all(), label=_("IssueFormStatus"),
                                    widget=widgets.Select(attrs=special_attributes))
    type = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), label=_("IssueFormType"),
                                          widget=widgets.SelectMultiple(attrs=special_attributes))

    class Meta:
        exclude = ["creation_time", "update_time", "project"]
        model = Issue


class ProjectForm(TranslationModelForm):
    start_date = forms.DateField(widget=widgets.DateInput(attrs={"type": "date",
                                                                 "class": "form-control"}),
                                 label=_("ProjectFormStartDate"))
    finish_date = forms.DateField(widget=widgets.DateInput(attrs={"type": "date",
                                                                 "class": "form-control"}),
                                  label=_("ProjectFormFinishDate"))
    project_name = forms.CharField(widget=widgets.TextInput(attrs=special_attributes), label=_("ProjectFormProjectName"))
    project_summary = forms.CharField(widget=widgets.Textarea(attrs=special_attributes),
                                      label=_("ProjectFormProjectSummary"))

    class Meta:
        exclude = ['users']
        model = Project


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")

issue_tracker/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, FormView, ListView
from webapp.models import Type, Status, Issue
from django.utils.http import urlencode
from webapp.forms import IssueForm, SearchForm
from django.urls import reverse
from django.db.models import Q


class IndexView(ListView):
    model = Issue
    template_name = 'index.html'
    context_object_name = 'issues'
    ordering = "-update_time"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["search"]


class IssueView(TemplateView):
    template_name = 'issue_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['issue_pk'])
        return context


class AddIssue(FormView):
    template_name = 'issue_create.html'
    form_class = IssueForm

    def form_valid(self, form):
        self.issue = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("issue_detail", kwargs={"issue_pk": self.issue.pk})


class UpdateIssue(FormView):
    template_name = "issue_update.html"
    form_class = IssueForm

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Issue, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issue"] = self.issue
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.issue
        return kwargs

    def form_valid(self, form):
        self.issue = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("issue_detail", kwargs={"issue_pk": self.issue.pk})


class DeleteIssue(View):
    def get(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        return render(request, 'issue_delete.html', context={'issue': issue})

    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

issue_tracker/webapp/views/issue_views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, DeleteView, CreateView, UpdateView
from webapp.models import Issue
from django.utils.http import urlencode
from webapp.forms import IssueForm, SearchForm
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin


class IndexView(ListView):
    model = Issue
    template_name = 'issues/index.html'
    context_object_name = 'issues'
    ordering = "-update_time"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["search"]


class AddIssue(PermissionRequiredMixin, CreateView):
    template_name = 'issues/create.html'
    form_class = IssueForm
    model = Issue
    permission_required = "webapp.add_issue"

    def get_success_url(self):
        return reverse("webapp:index")

class IssueView(TemplateView):
    template_name = 'issues/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['issue_pk'])
        return context


class UpdateIssue(UserPassesTestMixin, UpdateView):
    template_name = "issues/update.html"
    form_class = IssueForm
    model = Issue

    def test_func(self):
        pk = self.kwargs.get("pk")
        issue = get_object_or_404(Issue, pk=pk)
        return self.request.user in issue.project.users.all() and self.request.user.has_perm("webapp.change_issue")

    def get_success_url(self):
        return reverse("webapp:project_detail", kwargs={"pk": self.object.project.pk})


class DeleteIssue(UserPassesTestMixin, DeleteView):
    template_name = 'issues/delete.html'
    form_class = IssueForm
    model = Issue
    context_object_name = 'issues'

    def test_func(self):
        pk = self.kwargs.get("pk")
        issue = get_object_or_404(Issue, pk=pk)
        return self.request.user in issue.project.users.all() and self.request.user.has_perm("webapp.delete_issue")

    def get_success_url(self):
        id = self.kwargs.get("pk")
        project = get_object_or_404(Issue, pk=id)
        return reverse('webapp:project_detail', kwargs={"pk": project.project.pk})

issue_tracker/webapp/views/project_views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Project, Issue
from django.urls import reverse
from django.shortcuts import get_object_or_404
from webapp.forms import ProjectForm, IssueForm
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/index.html'
    paginate_by = 5


class ProjectDetailedView(DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issues"] = Issue.objects.filter(project=self.object.pk)
        project_users = self.get_object().users.all()
        context["project_users"] = project_users
        return context


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    model = Project
    template_name = 'projects/create.html'
    form_class = ProjectForm
    permission_required = "webapp.add_project"

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:project_list')


class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'projects/delete.html'
    model = Project
    context_object_name = 'project'

    def test_func(self):
        return self.request.user.has_perm("webapp.delete_project")

    def get_success_url(self):
        return reverse("webapp:project_list")


class ProjectUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'projects/update.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm

    def test_func(self):
        return self.request.user.has_perm("webapp.change_project")

    def get_success_url(self):
        return reverse("webapp:project_detail", kwargs={"pk": self.object.pk})


class ProjectCreateIssue(UserPassesTestMixin, CreateView):
    model = Issue
    template_name = "issues/create.html"
    form_class = IssueForm

    def test_func(self):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        return self.request.user in project.users.all() and self.request.user.has_perm("webapp.add_issue")

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        return reverse("webapp:project_detail", kwargs={"pk": project.pk})

issue_tracker/webapp/templates/projects/create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Create new project" %}
{% endblock %}

{% block content %}
    <h1>{% trans "Create new project" %}</h1>
        <form action="{% url 'webapp:project_add' %}" method="post">
            {% include 'partial/project_form.html' %}
          <button class="btn btn-primary mt-3">{% trans "Create" %}</button>
        </form>
{% endblock %}

issue_tracker/webapp/templates/projects/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Delete project" %}
{% endblock %}

{% block content %}
        <div class="container">
            <h1 class="text-center">{% trans "Are you sure want to delete project" %} "{{ project.project_name }}"?</h1>
            <form method="POST" action="{% url "webapp:project_delete" project.pk %}" class="text-center">
            {% csrf_token %}
                <div class="row">
                    <div class="col text-center">
                            <p><input class="btn btn-primary btn-lg btn-block mt-3" type="submit" value="{% trans "Yes" %}"></p>
                            <p><input class="btn btn-secondary btn-lg btn-block" type="button" value="{% trans "No" %}" onclick='location
                            .href="{% url "webapp:project_list"%}"'></p>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

issue_tracker/webapp/templates/projects/detail.html
{% extends 'base.html' %}
{% block add_issue_method %}{% url 'webapp:project_add_issue' project.pk %}{% endblock %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Details" %}{% endblock %}
{% block content %}
    <div class="product-detail">
        <h1>{{ project.project_name }}</h1><br>
        <p><b>{% trans "Description" %}</b>: {{ project.project_summary }}</p>
        <p><b>{% trans "Started at" %}</b>: {{ project.start_date }}</p>
        <p><b>{% trans "Deadline" %}</b>: {{ project.finish_date }}</p>
        <form action="{% url 'webapp:project_remove_user' project.pk %}" method="get">
            <p><b>{% trans "Participants" %}</b>:
            {% for user in project_users %}<a href="{% url "accounts:profile" user.pk %}">{{ user }}</a>
               {% if perms.auth.delete_user and request.user in project.users.all %}
                <button class="remove_user bi bi-person-x" name="user_id" value="{{ user.pk }}"></button>
                {% endif %}
            {% if forloop.last %}.{% else %},
            {% endif %}{% empty %}{% trans "No participants found." %}{% endfor %}</form>
                <form action="{% url 'webapp:project_add_user' project.pk %}" method="get">
                    {% if perms.auth.add_user and request.user in project.users.all %}
                    <button class="btn btn-primary btn-sm mb-3" >{% trans "Add a new user " %}<i class="bi bi-person-plus"></i></button>
                    {% endif %}
                </form>
    </div>

    <div class="row row-cols-1 row-cols-md-2">
    {% for issue in issues %}
        <div class="col mb-4">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title"><a href="{% url 'webapp:issue_detail' issue.pk %}">{{ issue.summary }}</a>
                    {% if perms.webapp.change_issue and request.user in project.users.all %}
                    <a href="{% url 'webapp:issue_update' issue.pk %}" class="bi bi-pencil-square"></a>
                    {% endif %}
                    {% if perms.webapp.delete_issue and request.user in project.users.all %}
                    <a href="{% url 'webapp:issue_delete' issue.pk %}" class="bi bi-file-earmark-minus"></a>
                    {% endif %}
                </h5>
                  <p class="card-text">{{ issue.description }}</p>
                  <p class="card-text"><small class="text-muted">{% trans "Last updated" %}: {{ issue.update_time }}</small></p>
                </div>
              </div>
        </div>
    {% empty %}
        <h4 class="container text-center mt-5">{% trans "No tasks found" %}</h4>
    {% endfor %}
    </div>
{% endblock %}

issue_tracker/webapp/templates/projects/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Main page" %}{% endblock %}

{% block content %}
    <h1 class="main_page">{% trans "Projects" %}</h1>
    {% include "partial/project_list.html" %}
    {% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}
{% endblock %}

issue_tracker/webapp/templates/projects/update.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Edit project" %}
{% endblock %}

{% block content %}
    <h1>{% trans "Edit project" %}</h1>
        <form action="{% url 'webapp:project_update' project.pk%}" method="post">
            {% include 'partial/project_form.html' %}
          <button class="btn btn-primary mt-3">{% trans "Edit" %}</button>
        </form>
{% endblock %}