issue_tracker/accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('list/', UserListView.as_view(), name='list'),
    path("<int:pk>/edit/", UserChangeView.as_view(), name="edit_profile"),
    path("<int:pk>/change-password/", ChangePasswordView.as_view(), name="change_password")
]

issue_tracker/issue_tracker/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls)
]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path('accounts/', include('accounts.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/webapp/urls.py
from django.urls import path
from webapp import views as webview
from accounts.views import RemoveFromProjectView, AddToProjectView

app_name = "webapp"

urlpatterns = [
    path('', webview.IndexView.as_view(), name='index'),
    path('issue/<int:issue_pk>/', webview.IssueView.as_view(), name='issue_detail'),
    path('issue/add/', webview.AddIssue.as_view(), name="issue_add"),
    path('issue/edit/<int:pk>/', webview.UpdateIssue.as_view(), name="issue_update"),
    path('issue/delete/<int:pk>', webview.DeleteIssue.as_view(), name="issue_delete"),
    path('projects-list/', webview.ProjectListView.as_view(), name='project_list'),
    path('detailed/<int:pk>', webview.ProjectDetailedView.as_view(), name='project_detail'),
    path('project/add', webview.ProjectCreateView.as_view(), name='project_add'),
    path('project/delete/<int:pk>', webview.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/update/<int:pk>', webview.ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/issue/add', webview.ProjectCreateIssue.as_view(), name='project_add_issue'),
    path('project/<int:project_pk>/account/remove/',
         RemoveFromProjectView.as_view(), name='project_remove_user'),
    path('project/<int:project_pk>/account/add/', AddToProjectView.as_view(), name='project_add_user')
]

issue_tracker/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name="profile",
        on_delete=models.CASCADE,
        verbose_name=_("ProfileUser")
    )
    avatar = models.ImageField(null=True, blank=True,
                               upload_to="avatars", verbose_name=_("ProfileAvatar"))
    github_link = models.URLField(null=True, blank=True,
                                  verbose_name=_("ProfileGithub"))
    about = models.TextField(null=True, blank=True,
                             verbose_name=_("ProfileAbout"))

    class Meta:
        verbose_name = _("ProfileVerboseName")
        verbose_name_plural = _("ProfilePluralName")

issue_tracker/webapp/models.py
from django.core.validators import BaseValidator
from django.db import models
from django.utils.deconstruct import deconstructible
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

@deconstructible
class MaxValueValidator(BaseValidator):
    message = "Value %(value)s has length %(show_value)d. Length should be less than %(limit_value)d"

    def clean(self, x):
        return len(x)

    def compare(self, a, b):
        return a > b


@deconstructible
class MinValueValidator(BaseValidator):
    message = "Value %(value)s has length %(show_value)d. Min Length should be more than %(limit_value)d"

    def clean(self, x):
        return len(x)

    def compare(self, a, b):
        return a < b


class Type(models.Model):
    title = models.CharField(max_length=20, null=False, blank=False, verbose_name=_('TypeTitle'))

    def __str__(self):
        return f'{self.title}'


class Status(models.Model):
    title = models.CharField(max_length=20, null=False, blank=False, verbose_name=_('StatusTitle'))

    def __str__(self):
        return f'{self.title}'


class Issue(models.Model):
    summary = models.CharField(max_length=30, validators=[MaxValueValidator(30)], null=False, blank=False,
                               verbose_name=_('IssueSummary'))
    description = models.TextField(max_length=2000, validators=[MinValueValidator(100)], blank=True, null=True,
                                   verbose_name=_('IssueDescription'))
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, verbose_name=_('IssueStatus'),
                               related_name='issues')
    type = models.ManyToManyField('webapp.Type', related_name='issues')
    creation_time = models.DateTimeField(auto_now_add=True, verbose_name=_('IssueCreationTime'))
    update_time = models.DateTimeField(auto_now=True, verbose_name=_('IssueUpdateTime'))
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.summary} ({self.status}, {self.type.get()})'


class Project(models.Model):
    start_date = models.DateField(verbose_name=_("ProjectStartDate"))
    finish_date = models.DateField(blank=True, verbose_name=_("ProjectFinishDate"))
    project_name = models.CharField(max_length=30, verbose_name=_("ProjectName"))
    project_summary = models.TextField(verbose_name=_("ProjectSummary"))
    users = models.ManyToManyField(User, verbose_name=_("ProjectUsers"))

    def __str__(self):
        return f'{self.project_name}'

issue_tracker/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import Issue, Status, Type, Project
from django.utils.translation import gettext_lazy as _
from modeltranslation.forms import TranslationModelForm

special_attributes = {"class": "form-control"}


class IssueForm(TranslationModelForm):
    summary = forms.CharField(widget=widgets.TextInput(attrs=special_attributes), label=_("IssueFormSummary"))
    description = forms.CharField(widget=widgets.Textarea(attrs=special_attributes), label=_("IssueFormDescription"))
    status = forms.ModelChoiceField(queryset=Status.objects.all(), label=_("IssueFormStatus"),
                                    widget=widgets.Select(attrs=special_attributes))
    type = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), label=_("IssueFormType"),
                                          widget=widgets.SelectMultiple(attrs=special_attributes))

    class Meta:
        exclude = ["creation_time", "update_time", "project"]
        model = Issue


class ProjectForm(TranslationModelForm):
    start_date = forms.DateField(widget=widgets.DateInput(attrs={"type": "date",
                                                                 "class": "form-control"}),
                                 label=_("ProjectFormStartDate"))
    finish_date = forms.DateField(widget=widgets.DateInput(attrs={"type": "date",
                                                                 "class": "form-control"}),
                                  label=_("ProjectFormFinishDate"))
    project_name = forms.CharField(widget=widgets.TextInput(attrs=special_attributes), label=_("ProjectFormProjectName"))
    project_summary = forms.CharField(widget=widgets.Textarea(attrs=special_attributes),
                                      label=_("ProjectFormProjectSummary"))

    class Meta:
        exclude = ['users']
        model = Project


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")

issue_tracker/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, FormView, ListView
from webapp.models import Type, Status, Issue
from django.utils.http import urlencode
from webapp.forms import IssueForm, SearchForm
from django.urls import reverse
from django.db.models import Q


class IndexView(ListView):
    model = Issue
    template_name = 'index.html'
    context_object_name = 'issues'
    ordering = "-update_time"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["search"]


class IssueView(TemplateView):
    template_name = 'issue_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['issue_pk'])
        return context


class AddIssue(FormView):
    template_name = 'issue_create.html'
    form_class = IssueForm

    def form_valid(self, form):
        self.issue = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("issue_detail", kwargs={"issue_pk": self.issue.pk})


class UpdateIssue(FormView):
    template_name = "issue_update.html"
    form_class = IssueForm

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Issue, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issue"] = self.issue
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.issue
        return kwargs

    def form_valid(self, form):
        self.issue = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("issue_detail", kwargs={"issue_pk": self.issue.pk})


class DeleteIssue(View):
    def get(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        return render(request, 'issue_delete.html', context={'issue': issue})

    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

issue_tracker/webapp/views/issue_views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, DeleteView, CreateView, UpdateView
from webapp.models import Issue
from django.utils.http import urlencode
from webapp.forms import IssueForm, SearchForm
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin


class IndexView(ListView):
    model = Issue
    template_name = 'issues/index.html'
    context_object_name = 'issues'
    ordering = "-update_time"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["search"]


class AddIssue(PermissionRequiredMixin, CreateView):
    template_name = 'issues/create.html'
    form_class = IssueForm
    model = Issue
    permission_required = "webapp.add_issue"

    def get_success_url(self):
        return reverse("webapp:index")

class IssueView(TemplateView):
    template_name = 'issues/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = get_object_or_404(Issue, pk=kwargs['issue_pk'])
        return context


class UpdateIssue(UserPassesTestMixin, UpdateView):
    template_name = "issues/update.html"
    form_class = IssueForm
    model = Issue

    def test_func(self):
        pk = self.kwargs.get("pk")
        issue = get_object_or_404(Issue, pk=pk)
        return self.request.user in issue.project.users.all() and self.request.user.has_perm("webapp.change_issue")

    def get_success_url(self):
        return reverse("webapp:project_detail", kwargs={"pk": self.object.project.pk})


class DeleteIssue(UserPassesTestMixin, DeleteView):
    template_name = 'issues/delete.html'
    form_class = IssueForm
    model = Issue
    context_object_name = 'issues'

    def test_func(self):
        pk = self.kwargs.get("pk")
        issue = get_object_or_404(Issue, pk=pk)
        return self.request.user in issue.project.users.all() and self.request.user.has_perm("webapp.delete_issue")

    def get_success_url(self):
        id = self.kwargs.get("pk")
        project = get_object_or_404(Issue, pk=id)
        return reverse('webapp:project_detail', kwargs={"pk": project.project.pk})

issue_tracker/webapp/views/project_views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Project, Issue
from django.urls import reverse
from django.shortcuts import get_object_or_404
from webapp.forms import ProjectForm, IssueForm
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/index.html'
    paginate_by = 5


class ProjectDetailedView(DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issues"] = Issue.objects.filter(project=self.object.pk)
        project_users = self.get_object().users.all()
        context["project_users"] = project_users
        return context


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    model = Project
    template_name = 'projects/create.html'
    form_class = ProjectForm
    permission_required = "webapp.add_project"

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:project_list')


class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'projects/delete.html'
    model = Project
    context_object_name = 'project'

    def test_func(self):
        return self.request.user.has_perm("webapp.delete_project")

    def get_success_url(self):
        return reverse("webapp:project_list")


class ProjectUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'projects/update.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm

    def test_func(self):
        return self.request.user.has_perm("webapp.change_project")

    def get_success_url(self):
        return reverse("webapp:project_detail", kwargs={"pk": self.object.pk})


class ProjectCreateIssue(UserPassesTestMixin, CreateView):
    model = Issue
    template_name = "issues/create.html"
    form_class = IssueForm

    def test_func(self):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        return self.request.user in project.users.all() and self.request.user.has_perm("webapp.add_issue")

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        project = get_object_or_404(Project, pk=pk)
        return reverse("webapp:project_detail", kwargs={"pk": project.pk})

issue_tracker/webapp/templates/base.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background-color: #4a4a4a">
    <div class="container">
      <a class="navbar-brand" href="{% url 'webapp:index' %}">{% trans "Issue Tracker" %}</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:index' %}">{% trans "Issues list" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_list' %}">{% trans "Projects list" %}</a>
          </li>
        {% if perms.accounts.view_profile %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:list' %}">{% trans "Users list" %}</a>
          </li>
        {% endif %}
         {% if perms.webapp.add_project or perms.webapp.add_issue and request.user in project.users.all %}
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans "Menu" %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if perms.webapp.add_project %}
                  <a class="dropdown-item" href="{% url 'webapp:project_add' %}">{% trans "Create a new project" %}</a>
                {% endif %}
                 {% if perms.webapp.add_issue and request.user in project.users.all %}
                  <a class="dropdown-item" href="
                    {% block add_issue_method %}{% url 'webapp:issue_add' %}{% endblock %}">
                      {% trans "Create a new issue" %}
                  </a>
                    {% endif %}
                </div>
             {% endif %}
             </li>
            <li class="nav-item dropdown">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% get_language_info for LANGUAGE_CODE as current_language %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ current_language.name_local }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for language in languages %}
                    <a class="dropdown-item" href="/{{ language.code }}">
                        {{ language.name_local }} ({{ language.code }})
                    </a>
                   {% endfor %}
                </div>
             </li>
                    {% if user.is_authenticated %}
           {% block menu_links %}{% endblock %}
           <li class="nav-item">
               <a class="nav-link active" href="{% url 'accounts:profile' user.pk %}">[{{ user.username }}]</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">{% trans "Logout" %}</a>
           </li>
       {% else %}
           <li class="menu-right"><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}" class="nav-link">{% trans "Login" %}</a></li>
           <li class="menu-right"><a href="{% url 'accounts:register' %}?next={{ request.get_full_path }}" class="nav-link">{% trans "Register" %}</a></li>
       {% endif %}
        {% include "partial/search_form.html" %}
        </ul>
      </div>
</nav>
    <div class="container">
    {% block content %}{% endblock %}
    </div>
    <div>
        <hr class="my-5">
    </div>
    <div class="container mt-5 mb-5">
        <p>Copyright &#169; Your Website 2021</p>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

issue_tracker/webapp/templates/issue_create.html
{% extends "base.html" %}

{% block title %}
    Create new issue
{% endblock %}

{% block content %}
    <h1>Create new issue</h1>
        <form action="{% url 'issue_add' %}" method="post">
            {% include 'partial/issue_form.html' %}
          <button class="btn btn-primary mt-3">Create</button>
        </form>
{% endblock %}

issue_tracker/webapp/templates/issue_delete.html
{% extends "base.html" %}
{% block title %}
    Delete Issue
{% endblock %}

{% block content %}
        <div class="container">
            <h1 class="text-center">Are you sure want to delete issue "{{ issue.summary }}"?</h1>
            <form method="POST" action="{% url "issue_delete" issue.pk %}" class="text-center">
            {% csrf_token %}
                <div class="row">
                    <div class="col text-center">
                            <p><input class="btn btn-primary btn-lg btn-block mt-3" type="submit" value="Yes"></p>
                            <p><input class="btn btn-secondary btn-lg btn-block" type="button" value="No" onclick='location
                            .href="{% url "index" %}"'></p>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

issue_tracker/webapp/templates/issue_detail.html
{% extends "base.html" %}

{% block title %}{{ issue.summary }}{% endblock %}

{% block content %}
    <div class="product-detail">
        <h1>{{ issue.summary }}</h1><span class="badge badge-primary">{{ issue.status }}</span> <p class="price
        badge badge-info">{{ issue.type.get }}</p>
        <p><b>Description</b>: {{ issue.description }}</p>
        <p><b>Created at</b>: {{ issue.creation_time }}</p>
        <p><b>Updated at</b>: {{ issue.update_time }}</p>
    </div>
{% endblock %}

issue_tracker/webapp/templates/issue_update.html
{% extends "base.html" %}

{% block title %}
    Edit issue
{% endblock %}

{% block content %}
    <h1>Edit product</h1>
        <form action="{% url 'issue_update' issue.pk%}" method="post">
            {% include 'partial/issue_form.html' %}
          <button class="btn btn-primary mt-3">Edit</button>
        </form>
{% endblock %}